### ISSUE TITLE
Editor Tools

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#4234]
The Editor Tools system should allow developers to create new tools for the scene view.

The tools should either be global tools (like move, rotate etc) or component specific tools that onlys how when an applicable GameObject is selected (think terrain, or maybe in the future ui).

```[tasklist]
### Tasks
- [x] Show a tool palette to allow switching between editor tools
- [x] Support component specific editor tools
- [x] Allow tools to create widgets, maybe an overlay, maybe floating tool windows.
- [ ] https://github.com/Facepunch/sbox-issues/issues/4328
```

**Comment by garrynewman** [comment]
Closing this as done, as I think we've covered the main points.. will make the terrain thing its own issue.
