### ISSUE TITLE
A few key features missing from networking

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4482]
### Describe the bug

1. `Connection.IsHost` always seems to return false
2. No easy way to get a list of all connections in the current lobby
3. No easy way to get the current lobby host
4. Can't get connection from network accessor on gameobject
5. Can't easily get SteamId or DisplayName without a Connection (which is hard to get due to issue 4)

### Expected behavior

1. `IsHost` should return true on the host connection
2. You should be able to do something simple like `NetworkManager.Connections` to get a list of all active connections to the current lobby
3. If issue 1 was solved then you could use link with issue 2 but it would also be nice to have a shorthand for directly grabbing the host (since one always exists)
4. You should be able to use `gameObject.Network.Owner` to access the Connection class that owns the gameobject directly
5. Issue 4 giving easier access to a Connection class would allow easier access for getting SteamId, DisplayName, ect so it's basically tied in.

```[tasklist]
### Tasks
- [x] `Connection.IsHost` always seems to return false
- [x] No easy way to get a list of all connections
- [x] No easy way to get the current host
- [x] Can't get connection from network accessor on gameobject
- [x] Can't easily get SteamId or DisplayName without a Connection (which is hard to get due to issue 4)
```

**Comment by garrynewman** [comment]
These are all relatively easy fixes

**Comment by MrBrax** [comment]
Does this mean we're getting closer to targeted RPC to connections and concmd authority?

**Comment by CarsonKompon** [comment]
I don't know how I missed this one, but I'd also like to request an easy way to get the current lobby (so you can get/set the privacy settings, name, ect)

**Comment by garrynewman** [comment]
Should be all solved now
