### ISSUE TITLE
Start Screen & Editor should be seperated

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#4593]
Instead of trying to support changing projects and maintaining no contamination in editor, it's much simpler if we only launch the editor with a project. Any content made should be in a project regardless of type, they're like workspaces.

```[tasklist]
### Tasks
- [x] Start Screen should launch projects in a new process with the `-project {sbproj}`
- [x] Start Screen should be a minimal Qt app, skip all the game mounting stuff so it's quick
- [x] We should let you have multiple editor projects open
```
