### ISSUE TITLE
Add/Sub/Incr/Decr to Set ActionGraph Nodes;   Create/Adjust Variable ActionGraph Nodes;   Replace Referenced Variables within ActionGraph

### ISSUE THREAD

**Issue by Sunday5465** [Facepunch/sbox-issues#5125]
### Feature Request

- Input/option to allow adding to, subtracting from, incrementing, or decrementing Set node values.
- Option to create new Variable nodes when Right Clicking an empty space within the Action Graph.
- Options within Variable nodes to select variables, change their source, type, name, and other adjustments.
- Option to replace all references of specific or missing variables within the Action Graph.

All of these features can be done in some other way or worked around manually. The purpose of their implementation would simply be to remove the time-consuming repetitiveness of handling certain oft-used functions within Action Graph.
```[tasklist]
### Tasks
- [ ] https://github.com/Facepunch/sbox-issues/issues/5160
- [x] Variable renaming in variable node context menu
- [x] Variable type selection in variable node context menu
```
